config/routes.rb
Rails.application.routes.draw do

  root 'sites#home'

  devise_for :users
 
  get 'sites/home', to: 'sites#signout'
  get '/budgets/:id/barchart', to: 'budgets#bar_chart', as: "budgetchart"
  get '/months/:id/piechart', to: 'months#pie_chart', as: "monthchart"

  resources :users, only: [:show, :edit, :update, :destroy], shallow: true do
    resources :budgets, only: [:show, :edit, :update] do
      resources :goals, only: [:index, :new, :create, :show, :edit, :update, :destroy]
      resources :months, only: [:new, :create, :show, :edit, :update, :destroy] do
        resources :categories, only: [:create, :update, :destroy]
      end
    end
  end
  
end

=begin

 Prefix Verb   URI Pattern                              Controller#Action
                    root GET    /                                        sites#home
        new_user_session GET    /users/sign_in(.:format)                 devise/sessions#new
            user_session POST   /users/sign_in(.:format)                 devise/sessions#create
    destroy_user_session DELETE /users/sign_out(.:format)                devise/sessions#destroy
           user_password POST   /users/password(.:format)                devise/passwords#create
       new_user_password GET    /users/password/new(.:format)            devise/passwords#new
      edit_user_password GET    /users/password/edit(.:format)           devise/passwords#edit
                         PATCH  /users/password(.:format)                devise/passwords#update
                         PUT    /users/password(.:format)                devise/passwords#update
cancel_user_registration GET    /users/cancel(.:format)                  devise/registrations#cancel
       user_registration POST   /users(.:format)                         devise/registrations#create
   new_user_registration GET    /users/sign_up(.:format)                 devise/registrations#new
  edit_user_registration GET    /users/edit(.:format)                    devise/registrations#edit
                         PATCH  /users(.:format)                         devise/registrations#update
                         PUT    /users(.:format)                         devise/registrations#update
                         DELETE /users(.:format)                         devise/registrations#destroy
              sites_home GET    /sites/home(.:format)                    sites#signout
             budgetchart GET    /budgets/:id/barchart(.:format)          budgets#bar_chart
              monthchart GET    /months/:id/piechart(.:format)           months#pie_chart
            budget_goals POST   /budgets/:budget_id/goals(.:format)      goals#create
         new_budget_goal GET    /budgets/:budget_id/goals/new(.:format)  goals#new
               edit_goal GET    /goals/:id/edit(.:format)                goals#edit
                    goal GET    /goals/:id(.:format)                     goals#show
                         PATCH  /goals/:id(.:format)                     goals#update
                         PUT    /goals/:id(.:format)                     goals#update
                         DELETE /goals/:id(.:format)                     goals#destroy
        month_categories POST   /months/:month_id/categories(.:format)   categories#create
                category PATCH  /categories/:id(.:format)                categories#update
                         PUT    /categories/:id(.:format)                categories#update
                         DELETE /categories/:id(.:format)                categories#destroy
           budget_months POST   /budgets/:budget_id/months(.:format)     months#create
        new_budget_month GET    /budgets/:budget_id/months/new(.:format) months#new
              edit_month GET    /months/:id/edit(.:format)               months#edit
                   month GET    /months/:id(.:format)                    months#show
                         PATCH  /months/:id(.:format)                    months#update
                         PUT    /months/:id(.:format)                    months#update
                         DELETE /months/:id(.:format)                    months#destroy
             edit_budget GET    /budgets/:id/edit(.:format)              budgets#edit
                  budget GET    /budgets/:id(.:format)                   budgets#show
                         PATCH  /budgets/:id(.:format)                   budgets#update
                         PUT    /budgets/:id(.:format)                   budgets#update
               edit_user GET    /users/:id/edit(.:format)                users#edit
                    user GET    /users/:id(.:format)                     users#show
                         PATCH  /users/:id(.:format)                     users#update
                         PUT    /users/:id(.:format)                     users#update
                         DELETE /users/:id(.:format)                     users#destroy

=end

app/models/month.rb
class Month < ActiveRecord::Base
  validates :projected_income, :projected_exp, :actual_income, :actual_exp, numericality: true
  validates :month_date, presence:true

  belongs_to :budget
  has_many :categories
  has_many :plans
  has_many :goals, through: :plans

  #method to set name to the name of the month if name is not provided

  def calc_actuals
    self.actual_exp = 0
    self.actual_income = 0
    categories = self.categories
    categories.each do |cat|
      self.actual_exp += cat.actuals if cat.expense
      self.actual_income += cat.actuals unless cat.expense
    end
    self.save
  end

  def calc_projected
    self.projected_exp = 0
    self.projected_income = 0
    categories = self.categories
    categories.each do |cat|
      self.projected_exp += cat.proj_val if cat.expense
      self.projected_income += cat.proj_val unless cat.expense
    end
    self.save
  end

  def current_month?
    today = Date.today
    given_date = self.month_date
    today.year == given_date.year && today.month == given_date.month
  end

  def month_exists?
    return false unless self.month_date
    !Month.where(budget_id: self.budget_id, month_date: self.month_date).empty?
  end

  def self.make_current_month budget_id
    create(
      name: Date.today.strftime("%B"),
      month_date: Date.today,
      projected_income: 0,
      projected_exp: 0,
      actual_income: 0,
      actual_exp: 0,
      budget_id: budget_id
      )
  end
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  before_action :login_check
  before_action :permission_check, :find_month, except: [:new, :create]
  def new
    @budget = Budget.find params[:budget_id]
  end

  def show
    Category.make_defaults(@month) if @month.categories.empty?
    @categories = @month.categories.order(:id)
    @expenses = []
    @income = []
    @categories.each do |cat|
      if cat.expense
        @expenses << cat
      else
        @income << cat
      end
    end
  end

  def edit
  end

  def pie_chart
    categories = @month.categories.order(:id)
    exp = []
    income = []
    unless categories.empty?
      categories.each do |cat|
          exp << [cat.name, cat.proj_val] if cat.expense
          income << [cat.name, cat.proj_val] unless cat.expense
      end
      respond_to do |format|
        format.json {render json: {expense: exp, income: income}}
      end
    else
      respond_to do |format|
        format.json {render json: nil}
      end
    end
  end

  def create
    month = Month.new month_params
    month.projected_income ||= 0
    month.projected_exp ||= 0
    month.actual_income ||= 0
    month.actual_exp ||= 0
    
    if !month.month_exists? && month.save
      month.budget = current_user.budget
      month.save
      flash[:success] = "Success: Month created"
      redirect_to month
    else
      flash[:alert] = "The month you attempted to create already exists" if month.month_exists?
      redirect_to :back, notice: "Please review your form below"
    end

  end

  def update
    #making sure duplicates are not added using edit
    if @month.month_date.year != month_params[:month_date].to_date.year && @month.month_date.month != month_params[:month_date].to_date.month 
      @month.month_date = params[:month_date]
      redirect_to :back, notice: "The date matches an existing month" if @month.month_exists?
    end

    if @month.update_attributes month_params
      redirect_to @month, notice: "Success: #{@month.name} updated"
    else
      redirect_to :back, notice: "Failed to update, please review your form below"
    end
  end

  def destroy
    category_with_goals = []
    @month.categories.each do |cat|
      category_with_goals << cat if cat.goal
    end
    unless category_with_goals.empty?
      redirect_to :back, notice: "Delete failed: This month contains a goal generated categories"
      return
    end

    @month.destroy
    redirect_to @month.budget, notice: "#{@month.name} has been deleted"
  end

  private
  def month_params
    params.require(:month).permit(:month_date, :name, :projected_income, :projected_exp, :actual_income, :actual_exp)
  end
  def login_check
    redirect_to new_user_session_path, notice: "Please sign in" unless current_user
    
  end

  def permission_check
    redirect_to root_path, notice: "Permission Denied" if current_user.id != Month.find(params[:id]).budget.user.id
  end

  def find_month
    @month = Month.find params[:id]
  end
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/views/months/edit.html.erb
<div class="after-nav container">
<h1>Edit Month</h1>

<p> Update details for your <%= @month.name %> below.</p><small><p>Note: If you have another month with the same date already, you will not be able to add a duplicate.</p><p>Your month's amounts are auto populated by the categories they have.</p></small>

<%= form_for @month do |f| %>
  <p><%= f.label :name, "Name: " %><br> <%= f.text_field :name %> </p>
  <p><%= f.label :month_date, "Date: " %> <br> <%= f.date_field :month_date %></p>
  <p><%= f.label :projected_income, "Projected Income (total):", class: "text-muted" %> <br> <%= f.number_field :projected_income, disabled: true, class: "text-muted bg-info" %></p>
  <p><%= f.label :projected_exp, "Projected Expense (total):", class: "text-muted" %> <br> <%= f.number_field :projected_exp, disabled: true, class: "text-muted bg-info" %></p>
  <%= f.submit "Update", class: "btn btn-primary" %>

<% end %>

</div>

app/views/months/new.html.erb
<div class="after-nav container">
<h1>New Month</h1>

<p> Add details for your new month below.</p><small><p>Note: If you have another month with the same date already, you will not be able to add a duplicate.</p></small>

<%= form_for [@budget,Month.new] do |f| %>
  <p><%= f.label :name, "Name: " %><br> <%= f.text_field :name, placeholder: "make it a fun name..." %></p>
  <p><%= f.label :month_date, "Date: " %><br> <%= f.date_field :month_date, placeholder: "(M/D/YYYY) 1st day of Month" %></p>
  <p><%= f.label :projected_income, "Projected Month Income: " %><br> <%= f.number_field :projected_income %></p>
  <p><%= f.label :projected_exp, "Projected Month Expense: " %><br> <%= f.number_field :projected_exp %></p>
  <%= f.submit "Add Month", class: "btn btn-primary" %>

<% end %>

</div>

app/views/months/show.html.erb
<div class="after-nav container">
<h1><span title="This page shows details of your month broken down into Income and Expenses. You may have as many categories as you need under both. If you have a goal it will have a category on this page."><%= @month.name %> <small><%= @month.month_date.strftime("%B") %> - <%= @month.month_date.year %> <small><%= link_to "edit month", edit_month_path, title: "Edit this month's detail" %> | <%= link_to "delete", month_path, method: :delete, data: {confirm: "Are you sure you want to delete this month: '#{@month.name}'?"} %></small></small> <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></span></h1>

<div class="addcat">
  <div class="catform">
  <h4 class="text-right"><a href="#"><span class="close-add glyphicon glyphicon-remove" aria-hidden="true"></span></a></h4>
    <h2 class="white-text">Add New Category</h2>
    <%= form_for [@month, Category.new] do |f| %>
      <%= f.text_field :name, placeholder: "Category Name", class: "form-control" %>
      <%= f.label :expense, "Expense?", class: "white-text" %> <%= f.check_box :expense %>
      <%= f.text_area :desc, placeholder: "Category Description", class: "form-control" %>
      <%= f.number_field :proj_val, placeholder: "Expected month amount", class: "form-control" %><br>
      <p class="white-text"><a id="show-periods" href="#">Add actual values for periods 1-4?</a></p>
      <div class="periods">
      <%= f.number_field :period1, placeholder: "Amount", class: "form-control" %>
      <%= f.number_field :period2, placeholder: "Amount", class: "form-control" %>
      <%= f.number_field :period3, placeholder: "Amount", class: "form-control" %>
      <%= f.number_field :period4, placeholder: "Amount", class: "form-control" %>
      </div>
      <%= f.submit "Add Category", class: "btn btn-primary", :disable_with => 'Submiting...' %>
    <% end %>
  </div>
</div>
<p><a href="#" class="cat-add-link", title="Add a new expense or income category">Add New Category</a></p>
<% if @income.any? %>
<h3 title="Income categories below">Income <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></h3><br>

<div class="row">
  <div class="col-sm-8">
    <ul>
<% @income.each do |cat| %>
    <% emo_val = (cat.proj_val - (cat.period1 + cat.period2 + cat.period3 + cat.period4)) %>
    <% emoji = "neut.png" %>
    <% emoji = "happy.png" if emo_val < 0 %>
    <% emoji = "sad.png" if emo_val > 0 %>

    <div class="disp">
    <!-- how to correctly ref images <img src="/assets/sad.png" alt="sad"> -->
    <li title="Click on the name to see details about this category. The changes you make are automatically saved and the faces change accordingly."><%= image_tag emoji %> <a class="show-cat-edit" style="color:green" href="#" title="Income catogory name: click me to see my details. Changes save automatically"><%= cat.name.capitalize %></a> -
        Projected: $<span class ="pval"><%= cat.proj_val %></span> | 
        Actual: $<span class='amt'><%= cat.period1 + cat.period2 + cat.period3 + cat.period4 %></span> <a href="#" title="click me to see the details for this income category. Changes save automatically"><span class="glyphicon glyphicon-plus show-cat-edit" aria-hidden="true"></span></a> 
        <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></li>
    
    <div class="cat-edit-form hidden">
    <%= form_for cat do |f| %>
    <div class="form-group form-inline">
      <%= f.label :name, "Name:" %>
      <%= f.text_field :name, class: "form-control"  %> 
      <%= link_to "Delete", category_path(cat), method: :delete, data: {confirm: "Are you sure you want to delete this category: '#{cat.name}'?"} %> |
      <a class="show-desc" href="#"><%= f.label :desc, "Description" %></a><br>
      <%= f.text_area :desc, size: "41x5", class: "desc form-control hidden" %> <br>
      <%= f.label :proj_val, "Projected Amount This Month:" %>
      <div class="input-group">
      <div class="input-group-addon">$</div>
      <%= f.number_field :proj_val, class: "form-control" %><br>
      </div>
      <h5 title="The fields below are for adding the actual values of your income for this category on about a weekly basis. Don't worry, your budget sends you emails to remind you to add these.">Actual income for periods (week): <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></h5>
      <div class="actuals">
        <div class="input-group">
        <div class="input-group-addon">1 - $</div>
        <%= f.number_field :period1, class: "form-control", title: "For actual income of period1 (~week1) of this month for this category" %>
        <div class="input-group-addon">3 - $</div>
        <%= f.number_field :period3, class: "form-control", title: "For actual income of period3 (~week3) of this month for this category" %>
        </div>
        <div class="input-group">
        <div class="input-group-addon">2 - $</div>
        <%= f.number_field :period2, class: "form-control", title: "For actual income of period2 (~week2) of this month for this category" %>
        <div class="input-group-addon">4 - $</div>
        <%= f.number_field :period4, class: "form-control", title: "For actual income of period4 (~week4) of this month for this category" %>
        </div>
        <p><a href='#' class="btn btn-primary dummy">Save</a></p>
      </div>
    </div>
    <% end %>
    </div>
    </div>

<% end %>
  </ul>
  </div>
  <div class="col-sm-4 right-side">
  <h4 title="The Pie Chart below shows the proportions of your projected income by category, for this month.">Projected Income Categories <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></h4>
    <div id="i-pie" data-url="<%= monthchart_path(@month) %>"></div>
  </div>
</div>
<% end %>
  <hr>

<% if @expenses.any? %>
<h3 title="Expense categories below">Expenses <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></h3><br>

<div class="row">
  <div class="col-sm-8">
    <ul>
<% @expenses.each do |cat| %>

    <% emo_val = cat.proj_val - (cat.period1 + cat.period2 + cat.period3 + cat.period4) %>
    <% emoji = "neut.png" %>
    <% emoji = "happy.png" if emo_val > 0 %>
    <%emoji = "sad.png" if emo_val < 0 %>

    <div class="disp">
    <li title="Click on the name to see details about this category. The changes you make are automatically saved and the faces change accordingly."><%= image_tag emoji %> <a class="show-cat-edit" style="color:red" href="#" title="Expense catogory name: click me to see my details. Changes save automatically."><%= cat.name.capitalize %></a> -
        Projected: $<span class ="pval"><%= cat.proj_val %></span> | 
        Actual: $<span class='amt'><%= cat.period1 + cat.period2 + cat.period3 + cat.period4 %></span> <a href="#" title="click me to see the details for this expense category. Changes save automatically."><span class="glyphicon glyphicon-plus show-cat-edit" aria-hidden="true"></span></a> <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></li>
    <div class="cat-edit-form hidden">
    <%= form_for cat do |f| %>
      <div class="form-group form-inline">
        <%= f.label :name, "Name:" %>
        <%= f.text_field :name, class: "form-control"  %> 
        <%= link_to "Delete", category_path(cat), method: :delete, data: {confirm: "Are you sure you want to delete this category: '#{cat.name}'?"} %> |
        <a class="show-desc" href="#"><%= f.label :desc, "Description" %></a><br>
        <%= f.text_area :desc, size: "41x5", class: "desc form-control hidden" %> <br>
        <%= f.label :proj_val, "Projected Expenses This Month:" %>
        <div class="input-group">
        <div class="input-group-addon">$</div>
        <%= f.number_field :proj_val, class: "form-control" %><br>
        </div>
        <h5 title="The fields below are for adding the actual values of your expenses for this category on about a weekly basis. Don't worry, your budget sends you emails to remind you to add these.">Actual expenses for periods (week): <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></h5>
        <div class="actuals">
          <div class="input-group">
          <div class="input-group-addon">1 - $</div>
          <%= f.number_field :period1, class: "form-control", title: "For actual expense of period1 (~week1) of this month for this category" %>
          <div class="input-group-addon">3 - $</div>
          <%= f.number_field :period3, class: "form-control", title: "For actual expense of period3 (~week3) of this month for this category"  %>
          </div>
          <div class="input-group">
          <div class="input-group-addon">2 - $</div>
          <%= f.number_field :period2, class: "form-control", title: "For actual expense of period2 (~week2) of this month for this category" %>
          <div class="input-group-addon">4 - $</div>
          <%= f.number_field :period4, class: "form-control", title: "For actual expense of period4 (~week4) of this month for this category"  %>
          </div>
          <p><a href='#' class="btn btn-primary dummy">Save</a></p>
        </div>
      </div>
    <% end %>
    </div>
    </div>

  <% end %>
    </ul>
  </div>
  <div class="col-sm-4 right-side">
  <h4 title="The Pie Chart below shows the proportions of your projected expenses by category, for this month.">Projected Expense Categories <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></h4>
    <div id="e-pie" data-url="<%= monthchart_path(@month) %>"></div>
  </div>
</div>
<% end %>
<hr>
<script>
  $('.nmonth').toggleClass('active');
</script>
</div>