config/routes.rb
Rails.application.routes.draw do

  root 'sites#home'

  devise_for :users
 
  get 'sites/home', to: 'sites#signout'
  get '/budgets/:id/barchart', to: 'budgets#bar_chart', as: "budgetchart"
  get '/months/:id/piechart', to: 'months#pie_chart', as: "monthchart"

  resources :users, only: [:show, :edit, :update, :destroy], shallow: true do
    resources :budgets, only: [:show, :edit, :update] do
      resources :goals, only: [:index, :new, :create, :show, :edit, :update, :destroy]
      resources :months, only: [:new, :create, :show, :edit, :update, :destroy] do
        resources :categories, only: [:create, :update, :destroy]
      end
    end
  end
  
end

=begin

 Prefix Verb   URI Pattern                              Controller#Action
                    root GET    /                                        sites#home
        new_user_session GET    /users/sign_in(.:format)                 devise/sessions#new
            user_session POST   /users/sign_in(.:format)                 devise/sessions#create
    destroy_user_session DELETE /users/sign_out(.:format)                devise/sessions#destroy
           user_password POST   /users/password(.:format)                devise/passwords#create
       new_user_password GET    /users/password/new(.:format)            devise/passwords#new
      edit_user_password GET    /users/password/edit(.:format)           devise/passwords#edit
                         PATCH  /users/password(.:format)                devise/passwords#update
                         PUT    /users/password(.:format)                devise/passwords#update
cancel_user_registration GET    /users/cancel(.:format)                  devise/registrations#cancel
       user_registration POST   /users(.:format)                         devise/registrations#create
   new_user_registration GET    /users/sign_up(.:format)                 devise/registrations#new
  edit_user_registration GET    /users/edit(.:format)                    devise/registrations#edit
                         PATCH  /users(.:format)                         devise/registrations#update
                         PUT    /users(.:format)                         devise/registrations#update
                         DELETE /users(.:format)                         devise/registrations#destroy
              sites_home GET    /sites/home(.:format)                    sites#signout
             budgetchart GET    /budgets/:id/barchart(.:format)          budgets#bar_chart
              monthchart GET    /months/:id/piechart(.:format)           months#pie_chart
            budget_goals POST   /budgets/:budget_id/goals(.:format)      goals#create
         new_budget_goal GET    /budgets/:budget_id/goals/new(.:format)  goals#new
               edit_goal GET    /goals/:id/edit(.:format)                goals#edit
                    goal GET    /goals/:id(.:format)                     goals#show
                         PATCH  /goals/:id(.:format)                     goals#update
                         PUT    /goals/:id(.:format)                     goals#update
                         DELETE /goals/:id(.:format)                     goals#destroy
        month_categories POST   /months/:month_id/categories(.:format)   categories#create
                category PATCH  /categories/:id(.:format)                categories#update
                         PUT    /categories/:id(.:format)                categories#update
                         DELETE /categories/:id(.:format)                categories#destroy
           budget_months POST   /budgets/:budget_id/months(.:format)     months#create
        new_budget_month GET    /budgets/:budget_id/months/new(.:format) months#new
              edit_month GET    /months/:id/edit(.:format)               months#edit
                   month GET    /months/:id(.:format)                    months#show
                         PATCH  /months/:id(.:format)                    months#update
                         PUT    /months/:id(.:format)                    months#update
                         DELETE /months/:id(.:format)                    months#destroy
             edit_budget GET    /budgets/:id/edit(.:format)              budgets#edit
                  budget GET    /budgets/:id(.:format)                   budgets#show
                         PATCH  /budgets/:id(.:format)                   budgets#update
                         PUT    /budgets/:id(.:format)                   budgets#update
               edit_user GET    /users/:id/edit(.:format)                users#edit
                    user GET    /users/:id(.:format)                     users#show
                         PATCH  /users/:id(.:format)                     users#update
                         PUT    /users/:id(.:format)                     users#update
                         DELETE /users/:id(.:format)                     users#destroy

=end

app/models/budget.rb
class Budget < ActiveRecord::Base
  validates :name, :user_id, presence: true

  belongs_to :user
  has_many :months, dependent: :destroy
  has_many :goals, dependent: :destroy

#returns the goal with the earliest end date of today or greater
  def earliest_goal
    self.goals.reduce {|res, goal| res = goal if goal.end_date < res.end_date && goal.end_date > Date.today}
  end

#returns the aggreagate goals' progress as a double for goals with end date of today or greater
  def goals_progress(type)
    exp = type == "expense" ? true : false
    sum_actual = 0
    sum_target = 0
    self.goals.each do |goal|
      if goal.is_expense? == exp && goal.end_date >= Date.today
        sum_target += goal.target_value
        sum_actual += goal.total_actual_value
      end
    end
    sum_target == 0 ? 0 : (sum_actual/sum_target) #0% for when there is no goal matching the type.
  end

#returns an array of goals ending today
  def goals_ending
    goals = self.goals
    goals.collect {|goal| goal if goal.end_date == Date.today}
  end
  
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :find_budget, :login_check
  before_action :permission_check, except: :create

  def show
    @months = @budget.months.order(month_date: :desc)
    Month.make_current_month(@budget.id) if @months.empty?
    @goals_ending = @budget.goals_ending
    @months.each do |month|
      month.calc_actuals
      month.calc_projected
    end
    @goals = @budget.goals
    

  end

  def bar_chart
    months = @budget.months
    expa = []
    inca = []
    expp = []
    incp = []
    months_filter = [Date.today - 365, Date.today + 365]
    months.each do |month|
      return if month.month_date < months_filter[0] || month.month_date > months_filter[1]
      month.calc_actuals
      month.calc_projected
      expa << [month.month_date.month.to_i, month.actual_exp.to_i]
      inca << [month.month_date.month.to_i, month.actual_income.to_i]
      expp << [month.month_date.month.to_i, month.projected_exp.to_i]
      incp << [month.month_date.month.to_i, month.projected_income.to_i]
    end
    respond_to do |format|
        format.json {render :json => {incomep: incp, expensep: expp, incomea: inca, expensea: expa}}
    end
  end

  def edit
  end

  def update
    if @budget.update_attributes budget_params
      flash[:success] = "Success: Budget updated"
      redirect_to @budget
    else
      redirect_to :back, alert: "Update failed, a budget reqires a name"
    end
  end

  private
  def budget_params
    params.require(:budget).permit(:name, :desc)
  end

  def find_budget
    @budget = Budget.find params[:id]
    @user = @budget.user
  end

  def login_check
    redirect_to new_user_session_path, notice: "Please sign in" unless current_user
    
  end
  def permission_check
    redirect_to root_path, notice: "Permission Denied" if current_user.id != Budget.find(params[:id]).user.id
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/edit.html.erb
<div class="after-nav container">
<h1>Editing <%= @user.first_name %>'s budget</h1>
<p>Please update the budget attributes below</p>

<%= form_for @budget do |f| %>
  <p><%= f.label :name, "Name: " %> <%= f.text_field :name %></p>
  <p>
  <%= f.label :desc, "Description:" %> <br><%= f.text_area :desc %>
  </p>
  <%= f.submit "Update", {class: "btn btn-primary"} %>

<% end %>
</div>

app/views/budgets/show.html.erb
<div class="after-nav container">

<h1><span title="This is your Budget's name. You may change it by clicking the 'Edit' link."><%= @user.first_name %>'s Budget <small><%= link_to "Edit", edit_budget_path(@budget), title: "edit your budget's information" %></small> <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></span></h1>

<% if @budget.desc && @budget.desc.length > 0 %>
      
      <p ><span title="Budget description. Click 'Edit' to change it" style="font-size: 1.25rem;">Description: <%= @budget.desc %></span></p>
    <% end %>
      <p>Below are all the months in <%= @budget.name %>. Different charts can be selected above the graph.</p>

<div class="row">
  <div class="col-sm-6">
    <p>You may add a new month <%= link_to "here", new_budget_month_path(@budget), title: "Click to add a new month to your budget" %>.</p>
    <% @months.each do |month| %>
      
      <h4><span title="The name you have given to this month followed by the actual calendar-month name"><%= link_to month.name, month %>: <%= month.month_date.strftime("%B") %> | <%= month.month_date.year %> <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></span></h4>
      <p><span title="Information about this month like the name you gave it and net projected and actual values. Click on the name to see more details.">Projected Net: <span title="Projected Income - Projected Expense for this particular month. Click on month name to update">$<%= month.projected_income - month.projected_exp %></span> Actual Net: <span title="Actual Income - Actual Expense for this particular month. Click on month name to update">$<%= month.actual_income - month.actual_exp %> </span> 
      <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></span>
      </p> 
      <p><%= link_to "Delete", month_path(month), method: :delete, data: {confirm: "Are you sure you want to delete this month: '#{month.name}'?"} %></p>
      <hr>
    <% end %>

<%= link_to "Add Month", new_budget_month_path(@budget), title: "Click to add a new month to your budget" %>
  </div>
  <div class="right-side col-sm-offset-1 col-sm-5 container-fluid">
      <div id="chart-selector" title="This sections displays different charts that show how your budget is doing over the months in your budget. You may select a chart of your choice from the list.">
        <label for="chart-sel">Select Chart: </label>
        <select name="chart-sel" id="chart-sel" title="Choose a desired graph to be displayed below">
          <option selected="selected">Actual Income Vs Actual Expense</option>
          <option>Projected Income Vs Projected Expense</option>
          <option>Projected Income Vs Actual Income</option>
          <option>Projected Expense Vs Actual Expense</option>
    </select>
    <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a>
    </div>
    <h4 class="chart-title text-center"></h4> <br>

    <div id="mon-bar" data-url="<%= budgetchart_path(@budget) %>"></div>
    <hr>

  </div>
</div>

</div>