config/routes.rb
Rails.application.routes.draw do

  root 'sites#home'

  devise_for :users
 
  get 'sites/home', to: 'sites#signout'
  get '/budgets/:id/barchart', to: 'budgets#bar_chart', as: "budgetchart"
  get '/months/:id/piechart', to: 'months#pie_chart', as: "monthchart"

  resources :users, only: [:show, :edit, :update, :destroy], shallow: true do
    resources :budgets, only: [:show, :edit, :update] do
      resources :goals, only: [:index, :new, :create, :show, :edit, :update, :destroy]
      resources :months, only: [:new, :create, :show, :edit, :update, :destroy] do
        resources :categories, only: [:create, :update, :destroy]
      end
    end
  end
  
end

=begin

 Prefix Verb   URI Pattern                              Controller#Action
                    root GET    /                                        sites#home
        new_user_session GET    /users/sign_in(.:format)                 devise/sessions#new
            user_session POST   /users/sign_in(.:format)                 devise/sessions#create
    destroy_user_session DELETE /users/sign_out(.:format)                devise/sessions#destroy
           user_password POST   /users/password(.:format)                devise/passwords#create
       new_user_password GET    /users/password/new(.:format)            devise/passwords#new
      edit_user_password GET    /users/password/edit(.:format)           devise/passwords#edit
                         PATCH  /users/password(.:format)                devise/passwords#update
                         PUT    /users/password(.:format)                devise/passwords#update
cancel_user_registration GET    /users/cancel(.:format)                  devise/registrations#cancel
       user_registration POST   /users(.:format)                         devise/registrations#create
   new_user_registration GET    /users/sign_up(.:format)                 devise/registrations#new
  edit_user_registration GET    /users/edit(.:format)                    devise/registrations#edit
                         PATCH  /users(.:format)                         devise/registrations#update
                         PUT    /users(.:format)                         devise/registrations#update
                         DELETE /users(.:format)                         devise/registrations#destroy
              sites_home GET    /sites/home(.:format)                    sites#signout
             budgetchart GET    /budgets/:id/barchart(.:format)          budgets#bar_chart
              monthchart GET    /months/:id/piechart(.:format)           months#pie_chart
            budget_goals POST   /budgets/:budget_id/goals(.:format)      goals#create
         new_budget_goal GET    /budgets/:budget_id/goals/new(.:format)  goals#new
               edit_goal GET    /goals/:id/edit(.:format)                goals#edit
                    goal GET    /goals/:id(.:format)                     goals#show
                         PATCH  /goals/:id(.:format)                     goals#update
                         PUT    /goals/:id(.:format)                     goals#update
                         DELETE /goals/:id(.:format)                     goals#destroy
        month_categories POST   /months/:month_id/categories(.:format)   categories#create
                category PATCH  /categories/:id(.:format)                categories#update
                         PUT    /categories/:id(.:format)                categories#update
                         DELETE /categories/:id(.:format)                categories#destroy
           budget_months POST   /budgets/:budget_id/months(.:format)     months#create
        new_budget_month GET    /budgets/:budget_id/months/new(.:format) months#new
              edit_month GET    /months/:id/edit(.:format)               months#edit
                   month GET    /months/:id(.:format)                    months#show
                         PATCH  /months/:id(.:format)                    months#update
                         PUT    /months/:id(.:format)                    months#update
                         DELETE /months/:id(.:format)                    months#destroy
             edit_budget GET    /budgets/:id/edit(.:format)              budgets#edit
                  budget GET    /budgets/:id(.:format)                   budgets#show
                         PATCH  /budgets/:id(.:format)                   budgets#update
                         PUT    /budgets/:id(.:format)                   budgets#update
               edit_user GET    /users/:id/edit(.:format)                users#edit
                    user GET    /users/:id(.:format)                     users#show
                         PATCH  /users/:id(.:format)                     users#update
                         PUT    /users/:id(.:format)                     users#update
                         DELETE /users/:id(.:format)                     users#destroy

=end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :end_date, :operator, :category, :target_value, :budget_id, presence: true

  belongs_to :budget
  has_many :plans, dependent: :destroy
  has_many :months, through: :plans
  has_many :categories, through: :plans

  def time_up?
    end_date >= Date.today
  end

  def goal_reached?
    actual_value = self.categories.reduce(0) {|sum, c| sum += c}
    is_expense ? target_value >= actual_value : target_value <= actual_value
  end

  def extend_time date
    e0 = self.start_date
    e1 = date
    e2 = self.end_date
    n_months = e2.year == e0.year ? e2.month - e0.month + 1 : (12 - e0.month) + e2.month + 1

    m_val = self.target_value / n_months
    e1 = e1.advance(months: +1)

    until e1 > e2
      c = self.make_category(e1, m_val)
      Plan.make_generic c.month, self, m_val, c
      e1 = e1.advance(months: +1)
    end
  end

  def dec_time
    e = self.end_date.advance(months: +1)
    cats = self.categories
    
      cats.each do |cat|
        plan = cat.plan

        if cat.month.month_date >= e
          plan.destroy
          cat.destroy 
        end
      end
  end

  def expense_goal?
    self.categories[0].expense
  end

  def total_actual_value
    self.categories.reduce(0) {|sum, cat| sum += cat.actuals}
  end

  def make_category date, m_val
    month = Month.new(
        name: date.strftime("%B"),
        month_date: date,
        projected_income: 0,
        projected_exp: 0,
        actual_income: 0,
        actual_exp: 0,
        budget_id: self.budget_id
        )
      if month.month_exists?
        month = Month.where(month_date: month.month_date)[0]
      else
        month.save
        Category.make_defaults(month)
      end
      
      c = Category.create(name: "Goal - " + self.category, 
        expense: self.is_expense, 
        desc: "Goal (#{self.name}) generated category", 
        month_id: month.id, 
        proj_val: m_val, 
        period1: 0, period2: 0, period3: 0, period4: 0)
      month.categories << c
      month.save
      c
  end

  def make_plans
    s = self.start_date
    e = self.end_date
    n_months = e.year == s.year ? e.month - s.month + 1 : (12 - s.month) + e.month + 1 #'+1' because the starting month is included

    m_val = self.target_value / n_months
    
    until s > e
      c = self.make_category(s, m_val)
      Plan.make_generic c.month, self, m_val, c
      s = s.advance(months: +1)
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @budget = Budget.find params[:budget_id]
    @goals = @budget.goals
    @t = Time.new( Time.now.year, Time.now.month)
    @earliest = @budget.earliest_goal
    @goals_inc_progress = "#{(@budget.goals_progress('income') * 100).round(1)}% actual savings toward target."
    @goals_exp_progress = "#{(@budget.goals_progress('expense') * 100).round(1)} of target expanses spent"
  end

  def show
    @goal = Goal.find params[:id]
    @cats = @goal.categories #categories associated with this goal
    @total = @cats.reduce(0) {|s, c| s + c.actuals}
    
  end

  def create
    budget = Budget.find params[:budget_id]
    goal = Goal.new goal_params
    goal.budget = budget

    sd = goal_params[:start_date].partition('-')
    ed = goal_params[:end_date].partition('-')
    
    goal.start_date = Date.new(sd[0].to_i, sd[2].to_i)
    goal.end_date = Date.new(ed[0].to_i, ed[2].to_i)
    t = Date.today #storing current time
    t1 = Date.new(t.month > 1 ? t.year + 1 : t.year, t.month) # a year out from today
    date_range = [(Date.new( t.year, t.month) - 3600), t1 ]
    
    if goal.start_date < date_range[0] || goal.start_date > date_range[1] || goal.end_date >= date_range[1] #ensures that goals timeline are at most one year from current month
      redirect_to :back, notice:"Your goal dates are out of the one year range from today" 
      return
    end

    if goal.save
      goal.make_plans
      redirect_to goal, notice: "New goal-#{goal.name} has been added!"
    else
      # binding.pry
      redirect_to :back, notice: "Goal not added, please review the goal form"
    end
  end

  def update
    goal = Goal.find params[:id]
    g1 = [goal.target_value, goal.end_date]
    p_ed = goal_params[:end_date].concat("-1").to_date
    if p_ed > goal.start_date.advance(years: +1) || p_ed < goal.start_date
      redirect_to :back, notice: "End date must be within 12 months of start date"
      return
    end

    goal.update_attributes goal_params
    goal.end_date = p_ed
    goal.target_value = goal_params[:target_value].to_i
    goal.save
    unless g1[1] == goal.end_date
      goal.extend_time(g1[1]) if g1[1] < goal.end_date
      goal.dec_time if g1[1] > goal.end_date
    end
    unless g1[0] == goal.target_value
      cats = goal.categories
      cats.each do|c| 
        c1 = Category.find c.id
        c1.proj_val = (goal.target_value / cats.length)
        c1.save
      end
    end
    goal.save
    redirect_to goal, notice: "Goal Updated Successfully"
  end

  def destroy
    #find goal and get the months associated with it
    #find categories connected to the goal and destroy them
    #Finally destroy the goal, which will destroy the plan
    goal = Goal.find params[:id]
    # goal. categories
    goal.destroy
    redirect_to budget_goals_path(goal.budget)
  end

  private
  def goal_params
    params.require(:goal).permit(:name, :start_date, :end_date, :category, :is_expense, :operator, :target_value)
  end

  def login_check
    redirect_to new_user_session_path, notice: "Please sign in" unless current_user  
  end

  def permission_check
    redirect_to root_path, notice: "Permission Denied" if current_user.id != Budget.find(params[:budget_id]).user.id
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/index.html.erb
<div class="after-nav container">
<div class="addgoal">
  <div class="goalform">
  <h4 class="text-right"><a href="#"><span class="close-add glyphicon glyphicon-remove" aria-hidden="true"></span></a></h4>
    <h2 class="white-text">Add New Goal</h2> 
    <%= form_for [@budget, Goal.new] do |f| %>
    <p><%= f.text_field :name, class: "form-control", placeholder: "Goal name" %></p>
    <p><%= f.label :start_date, "Start Month: ", class: "white-text" %> <br> <%= f.month_field :start_date, class: "form-control" %></p>
    <p><%= f.label :end_date, "End Month: ", class: "white-text" %> <br> <%= f.month_field :end_date, class: "form-control" %></p>
    <p><%= f.text_field :category, class: "form-control", placeholder: "Name the category" %></p>
    <p><%= f.label :is_expense, "Is the category an expense?", class: "white-text" %> <%= f.check_box :is_expense %></p>
    <p> <%= f.label :operator, "Goal Condition: ", class: "white-text" %> <%= f.select :operator, options_for_select([['>=', "greater"], ['<=', "less"]]), class: "form-control" %></p>
    <p><%= f.number_field :target_value, placeholder: "Target value", class: "form-control" %></p>
    <p><%= f.submit "Add New", class: "btn btn-primary" %></p>
    <% end %>
  </div>
</div>

  <h1><span title="Here is a list of all your goals. Clicking on the names show you more detail about each goal."><%= current_user.first_name %>'s Goals <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></span></h1>

  <% if @goals.length < 1 %>
    <p>Your budget currently has no goals. Add a goal <%= link_to "here.", "#", class: "goal-add-link" %></p>
  <% else %>
  <div class="col-sm-8">
    <p>Below is a list of your goals. Please click the name of a goal to see its details or edit it. You may add a new goal <%= link_to "here", "#", class: "goal-add-link" %></p>
    <ul>
      <% @goals.each do |goal| %>
      <li>
      <h4><%= link_to goal.name, goal %></h4> <%= link_to "delete", goal_path(goal), method: :delete, data: {confirm: "Are you sure you want to delete this goal?"} %>
      <hr>
      </li>
      <% end %>
    </ul>

    <p><%= link_to "Add New Goal", "#", class: "goal-add-link" %></p>
    </div>
    <div class="goal-statistics right-side col-sm-4">
    <% if @goals.length > 0 %>
      <h3>Goals Stats</h3> <br>
      <h4>Number of Goals:</h4>
      <p><%= @goals.length %> goal<%= 's' if @goals.length > 1 %></p>
      <h4>Goal with Earliest Deadline:</h4>
      <p><%= link_to @earliest.name, @earliest %> - <%= @earliest.end_date %></p>
      <h4>All Income Progress:</h4>
      <p><%= @goals_inc_progress %></p>
      <h4>All Expense Progress:</h4>
      <p style="border:none"><%= @goals_exp_progress %></p> <br>
      <% end %>
    </div>
  <% end %>
</div>

app/views/goals/show.html.erb
<div class="after-nav container">
  <h1 class="page-header" title="This page shows a summary of your progress toward your goal. It shows overall performance and breaks it down into the different months involved; click the name of the month to see."><%= @goal.name %> - Goal <small><%= "#{@goal.start_date} - #{@goal.end_date}" %> <small> <%= link_to "edit", "#", class: "t-goal-edit" %> | <%= link_to "delete", @goal, method: :delete, data: {confirm: "Are you sure you want to delete this goal?"} %></small></small> <a href="#"> <%= image_tag "info-grey.png", class: "itips" %></a></h1>

  <div class="goal-edit">
    <%= form_for @goal do |f| %>
      <%= f.text_field :name %>
      <%= f.text_field :category %>
      <%= f.number_field :target_value %>
      <%= f.month_field :end_date %>
      <%= f.submit "Update", class: "btn btn-primary" %>
    <% end %>
  </div>

  <div>
  <h3>
    <span class="label label-info">Days to go <span class="badge"><%= (@goal.end_date - Date.today).to_i %></span></span>
    <span class="label label-info">Target Value <span class="badge"><%= number_to_currency(@goal.target_value) %></span></span>
    <span class="label label-info"> <%= @goal.is_expense ? "Current Total Expense" : "Current Total Income" %> <span class="badge"><%= number_to_currency(@total) %></span></span>
    </h3>
  </div>

  <div class="goal-bar"><div 
  <% if @goal.is_expense %>
    <% if @total < @goal.target_value %>
    class="in-bar" 
      style="width:<%= (@total / @goal.target_value) *100 %>%"
    <% else %>
    class = "in-bar2" 
    <% end %>
  <% else %>
    class="in-bar" 
    style="width:<%= (@total > @goal.target_value ? 100 : @total / @goal.target_value) * 100 %>%"
  <% end %>
  ></div></div> <br>

  <div class="goal-cats">
    <div id="accordion">
      <% @cats.each do |cat| %>
      <h4><%= "#{cat.month.month_date.strftime('%B')} - #{cat.name}" %></h4>
      <div>
        <p>Progress: <%= ((cat.actuals * 100)/cat.proj_val).round(2) %>% of limit <%= @goal.is_expense ? "spent" : "saved" %> :<%= link_to "View Month", cat.month %></p>
        <div class="goal-bar"><div class="<%= (cat.actuals > cat.proj_val && @goal.is_expense) ? 'in-bar2' : 'in-bar' %>" style="width:<%= cat.actuals > cat.proj_val ? 100 : (cat.actuals/cat.proj_val) * 100 %>%"></div></div>
      </div>
      <% end %>
    </div>
  </div>

</div>