config/routes.rb
Rails.application.routes.draw do

  root 'sites#home'

  devise_for :users
 
  get 'sites/home', to: 'sites#signout'
  get '/budgets/:id/barchart', to: 'budgets#bar_chart', as: "budgetchart"
  get '/months/:id/piechart', to: 'months#pie_chart', as: "monthchart"

  resources :users, only: [:show, :edit, :update, :destroy], shallow: true do
    resources :budgets, only: [:show, :edit, :update] do
      resources :goals, only: [:index, :new, :create, :show, :edit, :update, :destroy]
      resources :months, only: [:new, :create, :show, :edit, :update, :destroy] do
        resources :categories, only: [:create, :update, :destroy]
      end
    end
  end
  
end

=begin

 Prefix Verb   URI Pattern                              Controller#Action
                    root GET    /                                        sites#home
        new_user_session GET    /users/sign_in(.:format)                 devise/sessions#new
            user_session POST   /users/sign_in(.:format)                 devise/sessions#create
    destroy_user_session DELETE /users/sign_out(.:format)                devise/sessions#destroy
           user_password POST   /users/password(.:format)                devise/passwords#create
       new_user_password GET    /users/password/new(.:format)            devise/passwords#new
      edit_user_password GET    /users/password/edit(.:format)           devise/passwords#edit
                         PATCH  /users/password(.:format)                devise/passwords#update
                         PUT    /users/password(.:format)                devise/passwords#update
cancel_user_registration GET    /users/cancel(.:format)                  devise/registrations#cancel
       user_registration POST   /users(.:format)                         devise/registrations#create
   new_user_registration GET    /users/sign_up(.:format)                 devise/registrations#new
  edit_user_registration GET    /users/edit(.:format)                    devise/registrations#edit
                         PATCH  /users(.:format)                         devise/registrations#update
                         PUT    /users(.:format)                         devise/registrations#update
                         DELETE /users(.:format)                         devise/registrations#destroy
              sites_home GET    /sites/home(.:format)                    sites#signout
             budgetchart GET    /budgets/:id/barchart(.:format)          budgets#bar_chart
              monthchart GET    /months/:id/piechart(.:format)           months#pie_chart
            budget_goals POST   /budgets/:budget_id/goals(.:format)      goals#create
         new_budget_goal GET    /budgets/:budget_id/goals/new(.:format)  goals#new
               edit_goal GET    /goals/:id/edit(.:format)                goals#edit
                    goal GET    /goals/:id(.:format)                     goals#show
                         PATCH  /goals/:id(.:format)                     goals#update
                         PUT    /goals/:id(.:format)                     goals#update
                         DELETE /goals/:id(.:format)                     goals#destroy
        month_categories POST   /months/:month_id/categories(.:format)   categories#create
                category PATCH  /categories/:id(.:format)                categories#update
                         PUT    /categories/:id(.:format)                categories#update
                         DELETE /categories/:id(.:format)                categories#destroy
           budget_months POST   /budgets/:budget_id/months(.:format)     months#create
        new_budget_month GET    /budgets/:budget_id/months/new(.:format) months#new
              edit_month GET    /months/:id/edit(.:format)               months#edit
                   month GET    /months/:id(.:format)                    months#show
                         PATCH  /months/:id(.:format)                    months#update
                         PUT    /months/:id(.:format)                    months#update
                         DELETE /months/:id(.:format)                    months#destroy
             edit_budget GET    /budgets/:id/edit(.:format)              budgets#edit
                  budget GET    /budgets/:id(.:format)                   budgets#show
                         PATCH  /budgets/:id(.:format)                   budgets#update
                         PUT    /budgets/:id(.:format)                   budgets#update
               edit_user GET    /users/:id/edit(.:format)                users#edit
                    user GET    /users/:id(.:format)                     users#show
                         PATCH  /users/:id(.:format)                     users#update
                         PUT    /users/:id(.:format)                     users#update
                         DELETE /users/:id(.:format)                     users#destroy

=end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budgetapp</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script> -->
  
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
  <link href='https://fonts.googleapis.com/css?family=Muli|Indie+Flower|Dancing+Script|Pacifico' rel='stylesheet' type='text/css'>

<!-- JQuery UI -->
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
  
  <!--[if lte IE 8]><script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/excanvas.min.js"></script><![endif]-->
  

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
<% unless user_signed_in? %>
<nav class="navbar navbar-default navbar-fixed-top navbar-right">
  <div class="container">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Sign in", new_user_session_path %></li>
    </ul>
  </div>
</nav>
<% else %>
<nav class="navbar navbar-default navbar-fixed-top navbar-right">
  <div class="container">
    <ul class="nav navbar-nav">
      <li><%= link_to "Profile", user_path(current_user), class: "nprofile", title: "Link to your user details" %></li>
      <li><%= link_to "Months", budget_path(current_user.budget), class: "nmonth", title: "Link to the list of months in your budget" %></li>
      <li><%= link_to "Goals", budget_goals_path(current_user.budget), class: "goals", title: "Link to the goals page" %></li>
      <li><%= link_to "Help", root_path, class: "help", title: "Toggles tooltips on or off" %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</nav>
<% end %>
</header>
<% flash.each do |key, msg| %>
  <% if key == "notice" %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% elsif key == "alert" %>
    <%= content_tag(:div, msg, class: "alert alert-danger") %>
  <% elsif %>
    <%= content_tag(:div, msg, class: "alert alert-success") %>
  <% else %>
    <%= content_tag(:div, msg, class: "alert") %>
  <% end %>
<% end %>

<%= yield %>

<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
</body>
</html>